apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thanak81-api-tester-plz-certificate
  namespace: thanak81-api-tester-plz
spec:
  secretName: thanak81-api-tester-plz-secret-tls
  commonName: thanak81-api-tester-plz.assessify.org
  dnsNames:
  - thanak81-api-tester-plz.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
